apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lb-svc
  name: lb-svc
spec:
  ports:
  - name: alation-web
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-dep
  type: LoadBalancer
status:
  loadBalancer: {}
