-
  name: Start Minikube cluster
  hosts: all
  tasks:
    - name: Copy K8s mainifest files to servers
      ansible.builtin.copy:
        src: ../k8s/
        dest: /k8s
      become: yes
      
    - name: Deployed application
      command: kubectl create -f .
      args:
        chdir: /k8s