-
  name: Start Minikube cluster
  hosts: all
  tasks:
    - name: Delete all previously deployed application
      command: kubectl delete ../k8s/.

    - name: Deployed application
      command: kubectl create -f ../k8s/.