-
  name: Start Minikube cluster
  hosts: all
  tasks:
    - name: Copy K8s mainifest files to servers
      ansible.builtin.copy:
        src: ../k8s/
        dest: /k8s
      become: yes

    - name: Delete all previously deployed application
      command: kubectl delete .
      args:
        chdir: /k8s

    - name: Deployed application
      command: kubectl create -f /k8s/.
      args:
        chdir: /k8s